FROM bitnami/kafka:latest

ENV KAFKA_CFG_NODE_ID=1 \
    KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv \
    KAFKA_CFG_PROCESS_ROLES=broker,controller \
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
    KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 \
    KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-on-docker-production.up.railway.app:9093 \
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT \
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-on-docker-production.up.railway.app:9093 \
    KAFKA_CFG_MESSAGE_MAX_BYTES=200000000 \
    KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=200000000 \
    KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=200000000 \
    KAFKA_CFG_MAX_REQUEST_SIZE=200000000 \
    ALLOW_PLAINTEXT_LISTENER=yes

EXPOSE 9092 9093
